### ISSUE TITLE
Problem trying to run some code in Jupyter notebook.

### ISSUE THREAD

**Issue by rchiodo** [Microsoft/HDInsightVSCodeExtension#30]
This is the root cause:

```
Info 2021-12-04 15:12:41: KernelProcess error: Traceback (most recent call last):
  File "C:\Users\Inrix\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Inrix\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\sparkmagic\kernels\pysparkkernel\pysparkkernel.py", line 34, in <module>
    IPKernelApp.launch_instance(kernel_class=PySparkKernel)
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.initialize(argv)
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\traitlets\config\application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\ipykernel\kernelapp.py", line 647, in initialize
    self.init_kernel()
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\ipykernel\kernelapp.py", line 499, in init_kernel
    kernel = kernel_factory(parent=self, session=self.session,
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\traitlets\config\configurable.py", line 540, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\sparkmagic\kernels\pysparkkernel\pysparkkernel.py", line 26, in __init__
    super(PySparkKernel,
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\sparkmagic\kernels\wrapperkernel\sparkkernelbase.py", line 47, in __init__
    self._load_magics_extension()
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\sparkmagic\kernels\wrapperkernel\sparkkernelbase.py", line 75, in _load_magics_extension
    self._execute_cell(register_magics_code, True, False, shutdown_if_error=True,
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\sparkmagic\kernels\wrapperkernel\sparkkernelbase.py", line 107, in _execute_cell
    if shutdown_if_error and reply_content[u"status"] == u"error":
TypeError: 'coroutine' object is not subscriptable
```

The pyspark team would likely have more information on how to address this issue. Transferring.

_Originally posted by @rchiodo in https://github.com/microsoft/vscode-jupyter/issues/8440#issuecomment-987232976_

**Comment by rchiodo** [comment]
Please see the referenced issue.

**Comment by Inrixia** [comment]
Any update on this?
